#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Feb 19 16:55:22 2025

add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/img_process_tb.sv"
add_simulation "D:/2L676demo/img_sim_prj/img_sim_prj/sim/video_data_gen.sv"
add_simulation "D:/2L676demo/img__ycbcr_sim_prj/img_ycbcr_sim_prj/sim/RGB2YCbCr.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/area_bin.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/binarization.v"
add_simulation "D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/sim/matrix_3x3.v"
add_design D:/2L676demo/img_bin_sim_prj/img_bin_sim_prj/ipcore/fifo_matrix_buf/fifo_matrix_buf.idf
add_simulation "D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/sim/dilate.v"
add_simulation "D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/sim/erosion.v"
add_design D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/ipcore/fifo_line_buffer/fifo_line_buffer.idf
add_simulation "D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/sim/matrix_3x3_1bit.v"
remove_simulation "D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/sim/matrix_3x3.v"
add_design D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/ipcore/fifo_line_buffer_1bit/fifo_line_buffer_1bit.idf
remove_simulation "D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin_sim_prj/sim/area_bin.v"
remove_design D:/2L676demo/img_bin__ero_dil_sim_prj/img_bin__ero_dil_sim_prj/ipcore/fifo_line_buffer/fifo_line_buffer.idf
