#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sat Nov  1 23:39:17 2025

add_design "G:/pango_prj/a_b_success/project/source/defect.v"
add_design "G:/pango_prj/a_b_success/project/source/tb_defect.v"
remove_design -verilog "G:/pango_prj/a_b_success/project/source/tb_defect.v"
